-- module CheckUpDown where
--
-- import Matrix
--
-- -- isInRow :: [Element] -> Int -> Bool
-- -- isInRow (e:row) regionId | (getRegion e) == regionId =
-- --                             | otherwise = getHighest row regionId
-- --
-- -- --Verifica se é a maior pos da regiao
-- -- isHighest :: Matrix -> Int -> Int -> Bool
-- -- isHighest (row:mat) i regionId | (getHighest row = True
-- --
-- -- -- Verifica caso duas cedulas sejam verticalmente adjacentes o maior tem que estar na de cima
-- -- verifyUpBigger:: -- Decidir entradas
-- -- verifyUpBigger =
